kind: Service
apiVersion: v1
metadata:
  name: mongo-app
  namespace: a0583251203-dev
  uid: 3b11d83c-9679-408b-ad73-843ffe349d72
  resourceVersion: '2671738259'
  creationTimestamp: '2025-08-19T14:19:06Z'
  labels:
    app: mongo-app
    app.kubernetes.io/component: mongo-app
    app.kubernetes.io/instance: mongo-app
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: v1
      time: '2025-08-19T14:19:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":27017,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 172.30.95.228
  ipFamilies:
    - IPv4
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.95.228
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: mongo-app
status:
  loadBalancer: {}
